# export ANSIBLE_STDOUT_CALLBACK=debug before running this makes the output nicer
# ansible-playbook playbook.yaml -e instance_name=p1 -e desired_state=present
- hosts: localhost
  tasks:
    - name: Check variables
      ansible.builtin.assert:
        that:
          - desired_state == "present" or desired_state == "absent"

    - name: Block to check if we previously created instance_name and it still exists
      block:
        - name: Read terraform's tfstate
          ansible.builtin.include_vars: tf/terraform.tfstate

        - name: Ensure we have a valid instance to destroy
          block:
            - name: Get a list of display names
              ansible.builtin.set_fact:
                display_names: "{{ resources[1]['instances'] | map(attribute='attributes') | map(attribute='display_name') }}"

            - name: See if instance_name matches a display_name
              ansible.builtin.assert:
                that:
                  - "{{ instance_name in display_names }}"
                fail_msg: "Can't destroy '{{ instance_name }}'. I only know about {{ display_names }}."

        - name: Update known_hosts
          ansible.builtin.known_hosts:
            name: "{{ outputs['private-ip-for-compute-instance']['value'] }}"
            state: absent

      when: desired_state == "absent"

    # - name: Use the template to make the TF instance file
    #   ansible.builtin.template:
    #     src: tf_instance.j2
    #     dest: ./tf/instance.tf

    - name: Run terraform to create or destroy the instance for the DB
      community.general.terraform:
        project_path: "tf/"
        state: "{{ desired_state }}"
      environment:
        TF_VAR_tenancy_ocid: "{{ lookup('ansible.builtin.ini', 'tenancy', section='DEFAULT', file='~/.oci/config') }}"
        TF_VAR_user_ocid: "{{ lookup('ansible.builtin.ini', 'user', section='DEFAULT', file='~/.oci/config') }}"
        TF_VAR_private_key_path: "{{ lookup('ansible.builtin.ini', 'key_file', section='DEFAULT', file='~/.oci/config') }}"
        TF_VAR_fingerprint: "{{ lookup('ansible.builtin.ini', 'fingerprint', section='DEFAULT', file='~/.oci/config') }}"
        TF_VAR_region: "{{ lookup('ansible.builtin.ini', 'region', section='DEFAULT', file='~/.oci/config') }}"
        TF_VAR_instance_name: "{{ instance_name }}"
        TF_VAR_desired_state: "{{ desired_state }}"

    - name: Add newly created instance to 'just_created'
      block:
        - name: Read terraform's tfstate
          ansible.builtin.include_vars: tf/terraform.tfstate

        - name: debug
          debug:
            msg: "{{ outputs['public-ip-for-compute-instance']['value'] }}"

        - name: Add host to group 'just_created'
          ansible.builtin.add_host:
            host: "{{ outputs['private-ip-for-compute-instance']['value'] }}"
            # host: "{{ outputs['public-ip-for-compute-instance']['value'] }}"
            groups: just_created
            
        - name: debug
          debug:
            msg: "{{ outputs['ssh_key_fingerprint'] }}"

        - name: wait
          ansible.builtin.wait_for:
            port: 22
            host: "{{ outputs['private-ip-for-compute-instance']['value'] }}"
            search_regex: SSH
            delay: 10
            timeout: 25

        - name: Scan for SSH host keys.
          ansible.builtin.command: ssh-keyscan {{ outputs['private-ip-for-compute-instance']['value'] }} 2>/dev/null
          changed_when: false
          register: ssh_scan

        - name: debug
          debug:
            var: ssh_scan

        - name: Update known_hosts.
          ansible.builtin.known_hosts:
            key: "{{ item }}"
            name: "{{ outputs['private-ip-for-compute-instance']['value'] }}"
          with_items: "{{ ssh_scan.stdout_lines }}"

        # - name: Ensure ssh host key is known
        #   ansible.builtin.known_hosts:
        #     state: present
        #     name: "{{ outputs['private-ip-for-compute-instance']['value'] }}"
        #     key: "{{ lookup('pipe', 'ssh-keyscan -trsa ' + outputs['private-ip-for-compute-instance']['value']) }}"
            
        # - name: Ensure ssh host key is known
        #   ansible.builtin.lineinfile:
        #     dest: ~/.ssh/known_hosts
        #     create: yes
        #     state: present
        #     line: "{{ lookup('pipe', 'ssh-keyscan -trsa ' + outputs['private-ip-for-compute-instance']['value']) }}"
            
        # - name: Update known_hosts
        #   ansible.builtin.known_hosts:
        #     name: "{{ outputs['private-ip-for-compute-instance']['value'] }}"
        #     key: "{{ outputs['ssh_key_fingerprint'] }}"

      when: desired_state == "present"

- hosts: just_created
  tasks:
      - name: APT install prerequisites
        become: true
        ansible.builtin.apt:
          update_cache: yes
          pkg:
            - curl
            - ca-certificates
            - gnupg

      - name: APT updgrade all
        become: true
        ansible.builtin.apt:
          name: "*"
          state: latest
        register: t1

      - name: reboot
        become: true
        ansible.builtin.reboot:

      - name: Get PostgreSQL repo key
        become: true
        ansible.builtin.shell: 
          cmd: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null

      - name: Add PostgreSQL APT Repository
        become: true
        ansible.builtin.apt_repository:
          repo: deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main

      - name: APT install Postgres 15
        become: true
        ansible.builtin.apt:
          name: postgresql-15

